package me.teajay.talkingvillagers.config;

import me.shedaniel.autoconfig.ConfigData;
import me.shedaniel.autoconfig.annotation.Config;

@Config(name = "talkingvillagers")
public class ModConfig implements ConfigData {
    boolean autoGenerateDefaultVoices = true;
    boolean pitchVariance = true;
}
